baseurl = "http://www.cs.ox.ac.uk/projects/RSE/"
languageCode = "en-gb"
title = "Oxford RSE"
theme = "natrium"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"
googleAnalytics = "UA-48149829-6"
enableGitInfo = true

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

[[menu.main]]
    name = "People"
    url = "/people/"
    weight = -130

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = -120

[params]
    description = ""

    [params.logo]
    url = "rse_logo_small.svg"
    alt = "Oxford Research Software Engineering"
