baseurl = "https://www.cs.ox.ac.uk/projects/RSE/"
languageCode = "en-gb"
title = "Oxford RSE"
theme = "natrium"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsUseClasses = true
pygmentsCodefences = true
googleAnalytics = "UA-48149829-6"
enableGitInfo = true

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -150

[[menu.main]]
    name = "People"
    url = "/people/"
    weight = -140

[[menu.main]]
    name = "Jobs"
    url = "/jobs/"
    weight = -130

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = -120

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = -110

[params]
    description = ""

    [params.logo]
    url = "banner_ox_rse.svg"
    alt = "Oxford Research Software Engineering"
